kind: pipeline
name: default

steps:
  - name: publish
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - sleep 15 # give docker enough time to start
      - sh ./ci/run.sh
    environment:
      CLOUDFLARE_API_KEY:
        from_secret: "CLOUDFLARE_API_KEY"
      CLOUDFLARE_EMAIL: "sh@signalwerk.ch"
