name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[CI SKIP]')"

    steps:
      - uses: actions/checkout@v3

      - name: deploy DNS
        run: sh ./ci/run.sh